# Generated by Django 4.2.7 on 2025-08-01 12:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(help_text='Credit score out of 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('past_loans_paid_on_time_score', models.PositiveIntegerField(default=0)),
                ('loan_activity_current_year_score', models.PositiveIntegerField(default=0)),
                ('loan_approved_volume_score', models.PositiveIntegerField(default=0)),
                ('number_of_loans_taken_score', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'credit_scores',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('monthly_salary', models.PositiveIntegerField()),
                ('approved_limit', models.PositiveIntegerField()),
                ('current_debt', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of all current outstanding loan amounts', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tenure', models.PositiveIntegerField(help_text='Loan tenure in months')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('monthly_repayment', models.DecimalField(decimal_places=2, help_text='Monthly EMI amount', max_digits=10)),
                ('emis_paid_on_time', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.customer')),
            ],
            options={
                'db_table': 'loans',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='customers_phone_n_7d2329_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_id'], name='customers_custome_b85ebb_idx'),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_score', to='core.customer'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['customer', 'status'], name='loans_custome_81a6e8_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['start_date', 'end_date'], name='loans_start_d_5c9ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['loan_id'], name='loans_loan_id_413fca_idx'),
        ),
    ]
